"""Static sanity checks on the GpsArrow scaffold.

Not a compiler, but it catches the classes of error that make a fresh Gradle sync fail:
unresolved R.* resources, imports of symbols that don't exist, version-catalog aliases with
no entry, unbalanced braces, and android.* leaking into the pure-JVM :core module.
"""
import os
import re
import sys
from collections import defaultdict

# The repo root is the parent of this directory. This used to be "../GpsArrow", which was right
# only for a staging copy nested one level deeper — so the sweep silently ran against a copy and
# never against the tree that gets committed. Anchor on a file that must exist, and stop loudly
# if it doesn't, rather than reporting on whatever happens to be there.
ROOT = os.path.normpath(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if not os.path.exists(os.path.join(ROOT, "settings.gradle.kts")):
    sys.exit("no settings.gradle.kts under %s — this is not the repo root" % ROOT)
problems = []
notes = []


def walk(ext, under=""):
    base = os.path.join(ROOT, under)
    for dirpath, _dirs, files in os.walk(base):
        for f in files:
            if f.endswith(ext):
                yield os.path.join(dirpath, f)


# ---------------------------------------------------------------- 1. resources
res_defined = defaultdict(set)
for xml in walk(".xml", "app/src/main/res"):
    text = open(xml, encoding="utf-8").read()
    for m in re.finditer(r'<(string|color|style|dimen)\s+name="([^"]+)"', text):
        res_defined[m.group(1)].add(m.group(2))
    rel = os.path.relpath(xml, os.path.join(ROOT, "app/src/main/res"))
    folder, fname = rel.split(os.sep)[0], os.path.basename(xml)[:-4]
    kind = folder.split("-")[0]
    if kind in ("drawable", "mipmap", "xml", "layout"):
        res_defined[kind].add(fname)

refs = []
for src in list(walk(".kt", "app")) + list(walk(".xml", "app/src/main")):
    text = open(src, encoding="utf-8").read()
    for m in re.finditer(r"\bR\.(string|color|drawable|mipmap|style|xml)\.(\w+)", text):
        refs.append((src, m.group(1), m.group(2)))
    for m in re.finditer(r'"@(string|color|drawable|mipmap|style|xml)/(\w+)"', text):
        refs.append((src, m.group(1), m.group(2)))

for src, kind, name in refs:
    if name not in res_defined.get(kind, set()):
        # android.R.* and framework @android: refs are fine.
        problems.append(f"MISSING RESOURCE  @{kind}/{name}  referenced in {os.path.relpath(src, ROOT)}")

# ---------------------------------------------------------------- 2. internal symbols
declared = {}
for src in walk(".kt"):
    text = open(src, encoding="utf-8").read()
    pkg = re.search(r"^package\s+([\w.]+)", text, re.M)
    pkg = pkg.group(1) if pkg else ""
    for m in re.finditer(
        r"^(?:@\w+\s+)*(?:public |internal |private |abstract |open |sealed |data |value )*"
        r"(class|object|interface|enum class)\s+(\w+)",
        text,
        re.M,
    ):
        declared[f"{pkg}.{m.group(2)}"] = src
    # Top-level functions and vals.
    #
    # The modifier prefix is not optional decoration. This regex used to require the line to
    # begin with `fun`, so `internal fun megabytes(...)` — legal, and importable anywhere in the
    # same module — was never indexed, and any import of it was reported as unresolved. The class
    # regex above already allowed modifiers; this one did not, so the two disagreed about what
    # counts as a declaration. `internal` is used throughout this codebase, which made that a
    # false positive waiting to happen rather than a theoretical gap.
    MODS = r"^(?:@\w+\s+)*(?:public |internal |private |inline |suspend |external |tailrec )*"
    for m in re.finditer(MODS + r"(?:fun|val|const val|lateinit var|var)\s+(?:<[^>]+>\s+)?(\w+)",
                         text, re.M):
        declared[f"{pkg}.{m.group(1)}"] = src
    # extension functions declared at top level:  fun Foo.bar()
    for m in re.finditer(MODS + r"fun\s+[\w.<>]+\.(\w+)\s*\(", text, re.M):
        declared[f"{pkg}.{m.group(1)}"] = src

for src in walk(".kt"):
    text = open(src, encoding="utf-8").read()
    for m in re.finditer(r"^import\s+(dev\.gpsarrow\.[\w.]+)", text, re.M):
        symbol = m.group(1)
        if symbol.endswith(".R"):
            continue  # generated by AGP at build time
        if symbol in declared:
            continue
        # nested symbol, e.g. dev.gpsarrow.core.ParseResult.Format
        parent = symbol.rsplit(".", 1)[0]
        if parent in declared:
            continue
        problems.append(
            f"UNRESOLVED IMPORT  {symbol}  in {os.path.relpath(src, ROOT)}"
        )

# ------------------------------------------------- 2b. symbols USED but not reachable
#
# The check above walks imports and asks "does this resolve?". That direction is blind to a
# symbol used with no import at all, because there is no import line to inspect — which is
# exactly how CI run #7 shipped four unresolved references past a clean sweep. Kotlin needs an
# explicit import for a top-level function from another package, even though a member of an
# imported class needs none, and that asymmetry is easy to miss by eye.
#
# So walk the other direction: every USE of a project top-level function must be reachable from
# where it is used — same package, explicit import, wildcard import, or declared in that file.

TOP_FUN = re.compile(
    r"^(?:@\w+\s+)*(?:public |internal |private |inline |suspend )*"
    r"fun\s+(?:<[^>]+>\s+)?(?:([\w.<>?]+)\.)?(\w+)\s*\(",
    re.M,
)

file_info = {}
for src in walk(".kt"):
    text = open(src, encoding="utf-8").read()
    pkg = re.search(r"^package\s+([\w.]+)", text, re.M)
    imports, wildcards = set(), set()
    for m in re.finditer(r"^import\s+([\w.]+)(\.\*)?", text, re.M):
        (wildcards if m.group(2) else imports).add(
            m.group(1) if m.group(2) else m.group(1).rsplit(".", 1)[-1]
        )
    file_info[src] = {
        "pkg": pkg.group(1) if pkg else "",
        "text": text,
        "imports": imports,
        "wildcards": wildcards,
        "tops": {m.group(2) for m in TOP_FUN.finditer(text)},
    }

top_level_funs = defaultdict(set)
for src, i in file_info.items():
    for name in i["tops"]:
        top_level_funs[name].add(i["pkg"])

for src, i in file_info.items():
    body = re.sub(r"/\*.*?\*/", "", i["text"], flags=re.S)
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r'"""(?:[^"]|"(?!""))*"""', '""', body)
    body = re.sub(r'"(?:\\.|[^"\\\n])*"', '""', body)
    body = re.sub(r"^import[^\n]*", "", body, flags=re.M)
    # A declaration is not a usage.
    body = re.sub(r"\bfun\s+(?:<[^>]+>\s*)?(?:[\w.<>?]+\.)?\w+\s*\(", "fun (", body)

    for name, pkgs in top_level_funs.items():
        if name in i["tops"] or name in i["imports"] or i["pkg"] in pkgs:
            continue
        if pkgs & i["wildcards"]:
            continue
        # Only unambiguous names: declared in exactly one package project-wide, so a same-named
        # member function elsewhere cannot be what was meant.
        if len(pkgs) != 1:
            continue
        if re.search(r"(?<![\w.])" + re.escape(name) + r"\s*\(", body) or \
           re.search(r"\.\s*" + re.escape(name) + r"\s*\(", body):
            problems.append(
                f"UNIMPORTED USAGE  '{name}' (declared in {sorted(pkgs)[0]}) "
                f"used in {os.path.relpath(src, ROOT)}"
            )

# ------------------------------------------- 2c/2d/2e: the checks 2b could not make
#
# 2b above asks a narrower question than it appears to: "is this *declared* symbol reachable
# from where it is used?". It indexes only top-level FUNCTIONS, and — the deeper flaw — it can
# only consider names that already exist somewhere in the project, because it iterates the
# declaration index. A reference to a symbol declared nowhere at all is never a key in that
# index, so the branch that would flag it never runs.
#
# Run #11 was exactly that: an enum was deleted along with the function above it by an
# over-broad text edit, and eight references to it stayed invisible to a check whose entire
# purpose was to see them. 2b stays, because it catches *lowercase* top-level functions used
# without an import (run #7), which the capitalised-identifier scan does not.
#
# These live in their own files so each can be run, and broken deliberately, on its own — which
# is how they were verified this time: against the failing commit before being trusted.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import resolve_check      # noqa: E402
import exhaustive_check   # noqa: E402

for _f, _line, _name in resolve_check.scan(ROOT)[0]:
    problems.append(f"UNRESOLVED IDENTIFIER  '{_name}' in {_f}:{_line} resolves to nothing")

# 2c can only be sound because every external symbol is named in an explicit import.
for _src in walk(".kt"):
    if re.search(r"^import\s+[\w.]+\.\*$", open(_src, encoding="utf-8").read(), re.M):
        problems.append(
            f"WILDCARD IMPORT  {os.path.relpath(_src, ROOT)} — 2c cannot resolve through it"
        )

for _f, _line, _enum, _missing in exhaustive_check.scan(ROOT)[0]:
    problems.append(
        f"NON-EXHAUSTIVE WHEN  {_f}:{_line} over {_enum}, no else, missing: {_missing}"
    )


# ---------------------------------------------------------------- 3. :core purity
for src in walk(".kt", "core"):
    text = open(src, encoding="utf-8").read()
    for m in re.finditer(r"^import\s+(android[x]?\.[\w.]+)", text, re.M):
        problems.append(
            f":core PURITY  {os.path.relpath(src, ROOT)} imports {m.group(1)}"
        )

# ---------------------------------------------------------------- 4. version catalogue
catalog = open(os.path.join(ROOT, "gradle/libs.versions.toml"), encoding="utf-8").read()
lib_aliases, plugin_aliases, version_refs, versions = set(), set(), set(), set()
section = None
for line in catalog.splitlines():
    s = line.strip()
    if s.startswith("[") and s.endswith("]"):
        section = s[1:-1]
        continue
    m = re.match(r"^([\w.-]+)\s*=", s)
    if not m:
        continue
    if section == "libraries":
        lib_aliases.add(m.group(1))
    elif section == "plugins":
        plugin_aliases.add(m.group(1))
    elif section == "versions":
        versions.add(m.group(1))
    vr = re.search(r'version\.ref\s*=\s*"([^"]+)"', s)
    if vr:
        version_refs.add(vr.group(1))

for missing in sorted(version_refs - versions):
    problems.append(f"CATALOG  version.ref '{missing}' has no [versions] entry")


def normalise(alias):
    return alias.replace("-", ".")


declared_libs = {normalise(a) for a in lib_aliases}
declared_plugins = {normalise(a) for a in plugin_aliases}

for gradle_file in walk(".kts"):
    text = open(gradle_file, encoding="utf-8").read()
    for m in re.finditer(r"libs\.plugins\.([\w.]+)", text):
        if m.group(1) not in declared_plugins:
            problems.append(
                f"CATALOG  libs.plugins.{m.group(1)} not in [plugins] "
                f"({os.path.relpath(gradle_file, ROOT)})"
            )
    for m in re.finditer(r"libs\.(?!plugins\.|versions\.)([\w.]+)", text):
        if m.group(1) not in declared_libs:
            problems.append(
                f"CATALOG  libs.{m.group(1)} not in [libraries] "
                f"({os.path.relpath(gradle_file, ROOT)})"
            )

unused = declared_libs - {
    m.group(1)
    for gradle_file in walk(".kts")
    for m in re.finditer(r"libs\.(?!plugins\.|versions\.)([\w.]+)", open(gradle_file, encoding="utf-8").read())
}
if unused:
    notes.append("catalogue entries reserved for v1/v2: " + ", ".join(sorted(unused)))

# ---------------------------------------------------------------- 5. braces & modules
for src in list(walk(".kt")) + list(walk(".kts")):
    text = open(src, encoding="utf-8").read()
    stripped = re.sub(r'""".*?"""', '""', text, flags=re.S)
    # Char literals BEFORE string literals. Kotlin's `'"'` (a char holding a double quote)
    # would otherwise be read as the start of a string, swallowing everything up to the next
    # quote and desynchronising the whole file. That produced a phantom brace imbalance.
    stripped = re.sub(r"'(?:\\u[0-9a-fA-F]{4}|\\.|[^'\\])'", "'x'", stripped)
    stripped = re.sub(r'"(?:\\.|[^"\\])*"', '""', stripped)
    stripped = re.sub(r"//[^\n]*", "", stripped)
    stripped = re.sub(r"/\*.*?\*/", "", stripped, flags=re.S)
    if stripped.count("{") != stripped.count("}"):
        problems.append(
            f"BRACES  {os.path.relpath(src, ROOT)}: "
            f"{stripped.count('{')} open vs {stripped.count('}')} close"
        )
    if stripped.count("(") != stripped.count(")"):
        problems.append(f"PARENS  {os.path.relpath(src, ROOT)}")

settings = open(os.path.join(ROOT, "settings.gradle.kts"), encoding="utf-8").read()
for module in re.findall(r'^include\("([^"]+)"\)', settings, re.M):
    path = os.path.join(ROOT, module.strip(":").replace(":", os.sep))
    if not os.path.isfile(os.path.join(path, "build.gradle.kts")):
        problems.append(f"MODULE  {module} has no build.gradle.kts")

# ---------------------------------------------------------------- 6. manifest classes
manifest = open(os.path.join(ROOT, "app/src/main/AndroidManifest.xml"), encoding="utf-8").read()
namespace = re.search(r'namespace\s*=\s*"([^"]+)"', open(os.path.join(ROOT, "app/build.gradle.kts"), encoding="utf-8").read()).group(1)
for m in re.finditer(r'android:name="(\.[\w.]+)"', manifest):
    fq = namespace + m.group(1)
    if fq not in declared:
        problems.append(f"MANIFEST  class {fq} declared in the manifest does not exist")

# ---------------------------------------------------------------- report
kt = len(list(walk(".kt")))
print(f"Scanned {kt} Kotlin files under {ROOT}")
for n in notes:
    print("  note:", n)
if problems:
    print(f"\n{len(problems)} problem(s):")
    for p in problems:
        print("  -", p)
    sys.exit(1)
print("\nAll static checks passed.")
