# -*- coding: utf-8 -*-
"""strings_table.py -> verification/TRANSLATIONS.md.

TRANSLATIONS.md said in its own header that it was generated from the table. Nothing generated
it. It drifted to 191 of the table's 257 keys — 26% stale, naming the app by a name it no longer
uses, still showing a permission string that had been replaced, and missing every safety string
added after the day it was hand-written, `position_stale` and `value_unknown` among them. The
newest safety strings were exactly the absent ones, because absence grows from the end.

A document that claims to be generated and is not is worse than one that admits it is
hand-maintained, because the claim is the thing that stops anyone checking. This makes the claim
true.

Run after `emit_strings.py`; it refuses to run before, so the document can never describe strings
that are not in the app. Run it from anywhere: `python3 verification/emit_translations.py`.
"""
import os, re, sys
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from strings_table import STRINGS, COMPASS_POINTS, SAFETY_KEYS

# Anchored on a file that only exists at the repo root. Two of the three checkers here once
# resolved their root wrongly and reported success on nothing; see verification/README.md.
ROOT = os.path.normpath(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if not os.path.exists(os.path.join(ROOT, "settings.gradle.kts")):
    sys.exit("no settings.gradle.kts under %s — this is not the repo root" % ROOT)

RES = os.path.join(ROOT, "app", "src", "main", "res")
OUT = os.path.join(ROOT, "verification", "TRANSLATIONS.md")
LANGS = [("", "en", "English"), ("-fr", "fr", "Français"), ("-ar", "ar", "العربية")]

HEADER = """# {app} — the three languages, string by string

<!-- GENERATED by verification/emit_translations.py from verification/strings_table.py.
     Do not edit this file: edit the table and re-run the emitter. -->

Generated from `verification/strings_table.py` by `verification/emit_translations.py`. Every row
here is the table's own text, so the three columns cannot disagree with what the app ships — the
emitter refuses to write unless the three `strings.xml` files already carry this exact key set.

Rows marked **!** carry safety meaning: they report how good the position is, that it is old,
that a subsystem has failed, or that the app does not know something. They are translated
literally, at the cost of elegance, on the principle that a smooth translation which softens
"this position may be old" is the dangerous kind.

**The marks are a reviewed judgement, not something the emitter can infer.** They come from
`SAFETY_KEYS` in the table. A newly added string is unmarked until someone reads it and adds it
there, so an unmarked row means "not yet judged" as well as "not safety-carrying". {nsafe} of
{nkeys} rows are marked.

"""

FOOTER = """
Arabic keeps the Latin abbreviations: the sixteen-point rose has no compact Arabic
convention (the intercardinals spell out to three words), the bearing beside them is
already in Latin digits, and regional marine and aviation practice uses Latin.
"""


def cell(s):
    """Markdown table cell. The table has no pipes or newlines in it today; escape anyway, so
    that the day one arrives the document bends instead of silently losing a column."""
    return s.replace("\\", "\\\\").replace("|", "\\|").replace("\n", "<br>")


# ---------------------------------------------------------------- read the table
keys = [r[0] for r in STRINGS if r[0] != "SECTION"]
sections = [r[1] for r in STRINGS if r[0] == "SECTION"]
by_key = {r[0]: r for r in STRINGS if r[0] != "SECTION"}

# A checker that finds nothing to check has failed to run, and must say so.
if not keys or not sections:
    sys.exit("refusing to report success on an empty scan: %d keys, %d sections"
             % (len(keys), len(sections)))
if len(keys) != len(set(keys)):
    dupes = sorted({k for k in keys if keys.count(k) > 1})
    sys.exit("duplicate keys in the table: %s" % ", ".join(dupes))

# A rename must not silently drop a safety mark.
unknown = sorted(SAFETY_KEYS - set(keys))
if unknown:
    sys.exit("SAFETY_KEYS names %d key(s) that are not in the table — renamed or deleted?\n  %s"
             % (len(unknown), "\n  ".join(unknown)))

for _, lang, _ in LANGS:
    n = len(COMPASS_POINTS[lang])
    if n != 16:
        sys.exit("compass rose for %s has %d points, expected 16" % (lang, n))

# ------------------------------------------- the document must describe what actually ships
missing_res = [s for s, _, _ in LANGS
               if not os.path.exists(os.path.join(RES, "values%s" % s, "strings.xml"))]
if missing_res:
    sys.exit("no strings.xml for values%s — run emit_strings.py first"
             % ", values".join(missing_res))

for suffix, lang, _ in LANGS:
    path = os.path.join(RES, "values%s" % suffix, "strings.xml")
    root = ET.parse(path).getroot()
    shipped = [e.get("name") for e in root.findall("string")]
    if shipped != keys:
        only_res = sorted(set(shipped) - set(keys))
        only_tbl = sorted(set(keys) - set(shipped))
        sys.exit(
            "values%s/strings.xml is out of step with the table (%d keys there, %d here)\n"
            "  only in the xml : %s\n"
            "  only in the table: %s\n"
            "  run emit_strings.py first — this document may not describe strings the app "
            "does not have" % (suffix, len(shipped), len(keys),
                               ", ".join(only_res) or "none",
                               ", ".join(only_tbl) or "none"))
    rose = {a.get("name"): [i.text for i in a.findall("item")]
            for a in root.findall("string-array")}
    if rose.get("compass_points") != COMPASS_POINTS[lang]:
        sys.exit("values%s compass_points differs from the table — run emit_strings.py first"
                 % suffix)

app_name = by_key["app_name"][1]

# ---------------------------------------------------------------- emit
out = [HEADER.format(app=app_name, nsafe=len(SAFETY_KEYS), nkeys=len(keys))]
for row in STRINGS:
    if row[0] == "SECTION":
        out.append("\n## %s\n\n" % row[1])
        out.append("| | key | %s |\n" % " | ".join(name for _, _, name in LANGS))
        out.append("|---|---|%s\n" % ("---|" * len(LANGS)))
        continue
    mark = "**!**" if row[0] in SAFETY_KEYS else ""
    out.append("| %s | `%s` | %s |\n"
               % (mark, row[0], " | ".join(cell(row[i]) for i in (1, 2, 3))))

out.append("\n## Sixteen-point compass rose\n\n")
out.append("| index | %s |\n" % " | ".join(name for _, _, name in LANGS))
out.append("|---|%s\n" % ("---|" * len(LANGS)))
for i in range(16):
    out.append("| %d | %s |\n" % (i, " | ".join(cell(COMPASS_POINTS[lang][i])
                                                for _, lang, _ in LANGS)))
out.append(FOOTER)

with open(OUT, "w", encoding="utf-8") as f:
    f.write("".join(out))
print("wrote %s" % OUT)

# ------------------------------------------- read back what was written, not what was intended
# Several bugs in this project came from an edit that silently matched nothing. Parse the file
# that now exists and check it against the table it was supposed to come from.
text = open(OUT, encoding="utf-8").read()
rows = re.findall(r"^\| (\*\*!\*\*)? \| `([a-z0-9_]+)` \| (.*) \|$", text, re.M)
got_keys = [k for _, k, _ in rows]
if got_keys != keys:
    sys.exit("round-trip failed: parsed %d keys back out of %d written" % (len(got_keys), len(keys)))
got_safe = {k for m, k, _ in rows if m}
if got_safe != set(SAFETY_KEYS):
    sys.exit("round-trip failed: marks in the file are not SAFETY_KEYS\n  %s"
             % sorted(got_safe ^ set(SAFETY_KEYS)))
for _, k, body in rows:
    want = " | ".join(cell(by_key[k][i]) for i in (1, 2, 3))
    if body != want:
        sys.exit("round-trip failed on `%s`:\n  file : %s\n  table: %s" % (k, body, want))
if app_name not in text.splitlines()[0]:
    sys.exit("round-trip failed: the title does not name the app %r" % app_name)

print("\nOK: %d strings x 3 languages + a 16-item rose, in %d sections, %d marked safety-carrying"
      % (len(keys), len(sections), len(SAFETY_KEYS)))
print("    every row read back matches the table; every key matches all three strings.xml")
