package dev.gpsarrow.core

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * GENERATED by verification/pmtiles_header_fixtures.py - do not hand-edit.
 *
 * Every header below was built in Python straight from the spec's byte table, as an
 * implementation independent of Pmtiles.kt. A test that built its fixtures with the same
 * code it is testing would agree with any bug the parser has.
 */
class PmtilesTest {

    private fun bytes(hex: String) = ByteArray(hex.length / 2) {
        hex.substring(it * 2, it * 2 + 2).toInt(16).toByte()
    }

    /** the shape pmtiles extract actually produces */
    @Test
    fun `acceptsAWellFormedArchive`() {
        val header = bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 180001627L)
        assertTrue("expected a valid header, got $result", result is PmtilesCheck.Valid)
    }

    /** one byte short: the tile-data section now runs past the end of the file. This is the case that matters most - it is what a download interrupted at 99% looks like */
    @Test
    fun `rejectsATruncatedFile`() {
        val header = bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 180001626L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.FILE_TRUNCATED,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** half a file */
    @Test
    fun `rejectsAHalfDownloadedFile`() {
        val header = bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 90000813L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.FILE_TRUNCATED,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** an HTML error page or a PNG saved under the right name */
    @Test
    fun `rejectsAFileThatIsNotPmtilesAtAll`() {
        val header = bytes("89504e470d0a1a037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 180001627L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.NOT_A_PMTILES_FILE,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** a v4 archive this build cannot read */
    @Test
    fun `rejectsAFutureSpecVersion`() {
        val header = bytes("504d54696c6573047f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 180001627L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.UNSUPPORTED_VERSION,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** MapLibre's reader throws on anything but none/gzip, so catch it here where we can explain it */
    @Test
    fun `rejectsBrotliInternalCompression`() {
        val header = bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001030201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 180001627L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.UNSUPPORTED_COMPRESSION,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** same, for the tile data */
    @Test
    fun `rejectsBrotliTileCompression`() {
        val header = bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020301000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 180001627L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.UNSUPPORTED_COMPRESSION,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** a raster archive would render but no style rule would match */
    @Test
    fun `rejectsARasterArchive`() {
        val header = bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020202000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 180001627L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.NOT_VECTOR_TILES,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** min above max */
    @Test
    fun `rejectsAnImpossibleZoomRange`() {
        val header = bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f3050000000000010202010a0440bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 180001627L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.IMPOSSIBLE_ZOOM_RANGE,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** spec requires header+root inside the first 16 KiB */
    @Test
    fun `rejectsARootDirectoryPastTheSpecLimit`() {
        val header = bytes("504d54696c657303204e00000000000064000000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 200000000L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.ROOT_DIRECTORY_TOO_FAR,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** a u64 past Long.MAX_VALUE reads as negative rather than wrapping to a small positive */
    @Test
    fun `rejectsAnAbsurdSectionOffset`() {
        val header = bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b06000000000000000000000000000000000000000000800095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10")
        val result = Pmtiles.check(header, 180001627L)
        assertTrue("expected rejection, got $result", result is PmtilesCheck.Invalid)
        assertEquals(
            PmtilesProblem.NONSENSE_SECTION,
            (result as PmtilesCheck.Invalid).problem,
        )
    }

    /** The header's own numbers must survive the round trip, not just parse without error. */
    @Test
    fun `decodesTheHeaderFields`() {
        val result = Pmtiles.check(bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10"), 180001627L)
        val h = (result as PmtilesCheck.Valid).header
        assertEquals(0, h.minZoom)
        assertEquals(14, h.maxZoom)
        assertEquals(579860L, h.addressedTiles)
        assertEquals(400000L, h.tileEntries)
        assertEquals(390000L, h.tileContents)
        assertTrue(h.clustered)
        assertEquals(-17.10, h.west, 1e-7)
        assertEquals(20.77, h.south, 1e-7)
        assertEquals(-0.99, h.east, 1e-7)
        assertEquals(35.95, h.north, 1e-7)
    }

    /** Bounds are what decides whether an installed region covers where the user is. */
    @Test
    fun `boundsCoverCasablancaAndNotNouakchott`() {
        val result = Pmtiles.check(bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10"), 180001627L)
        val h = (result as PmtilesCheck.Valid).header
        assertTrue(h.covers(LatLon(33.5731, -7.5898)))
        assertTrue(!h.covers(LatLon(18.0735, -15.9582)))
    }

    /** A short read must be refused rather than indexed past the end. */
    @Test
    fun `rejectsAHeaderShorterThanTheSpecLength`() {
        val short = bytes("504d54696c6573037f00000000000000e8030000000000006704000000000000f4010000000000005b0600000000000000000000000000005b060000000000000095ba0a0000000014d9080000000000801a06000000000070f305000000000001020201000e40bfcef52040610c20f068ffe0886d150780b5a2fa007fed10").copyOf(100)
        val result = Pmtiles.check(short, 180001627L)
        assertEquals(
            PmtilesProblem.TRUNCATED_HEADER,
            (result as PmtilesCheck.Invalid).problem,
        )
    }
}
